### ISSUE TITLE
nodes_mode_shape_dofs for a bridge structure

### ISSUE THREAD

**Issue by Ayubirad** [marco-rosso-m/i-AOMA#1] opened 2023-08-18 11:52 UTC
Dear Dr. Rosso,

I hope this message finds you well. Firstly, I would like to express my gratitude for the exceptional package you have developed and the effort you have put into publishing the insightful paper on Intelligent Automatic Operational Modal Analysis. It has been an enlightening read.

I am reaching out to you today with a specific query regarding the definition of nodes_mode_shape_dofs for a bridge structure. As I delve into this topic, I find myself in need of guidance on this matter. If it is not too much trouble, could you kindly provide me with some guidance?
Also, we can not use this package on impact test data, correct?

Thank you once again for your invaluable contributions to the field, and I look forward to hearing from you.

Warm regards,
Mohammad

P.S. here are the sensors positions and directions on the bridge:
https://imgtr.ee/image/3MRxa

**Comment by marco-rosso-m** [comment] 2023-08-19 08:16
Dear Mohammad,

I have received your message by email, however I have noticed that you have already close the issue. I believe that you were able to fix your issue then. Anyway, thank you very much for your words of appreciation.

Thank you very much for your interest!

Best regards

ArtIStE - Artificial Intelligence in Structural Engineering
[http://www.civilml.polito.it/](http://www.civilml.polito.it/)
e-mail: marco.rosso@polito.it
Personal Website : [http://rossomarcomartino.flazio.com/](http://rossomarcomartino.flazio.com/)
PhD Student in Structural Civil Engineering at Politecnico di Torino

**Comment by Ayubirad** [comment] 2023-08-19 08:46
Dear Dr. Ross,

Thanks for your quick response. Actually, I deleted the issue since I sent
the email. Sorry for that. I would really appreciate your help on the
aforementioned issue.

**Comment by marco-rosso-m** [comment] 2023-08-20 06:35
Dear @Ayubirad ,

Consider for instance the 5-dofs problem. You have monitored 5 dofs (all in x direction) for the 5 nodes numbered 0,1,2,3, and 4. Since the problem is 2D, the file nodes_mode_shape_dofs has two columns (indicating the dofs x, first column, and y, second column, for every node in the domain of analysis encoded by the rows of the file).
This file is initialized -1 everywhere at the beginning, then you can connect which column of the data file is referred to each specific dof of the monitored node by setting the number of the data file column in each specific position.

![image](https://github.com/marco-rosso-m/i-AOMA/assets/94112589/c4d166fc-68e0-4d8e-9b77-9091314dd257)

I hope it is clearer now,

Best regards

Marco Martino Rosso

ArtIStE - Artificial Intelligence in Structural Engineering
http://www.civilml.polito.it/
e-mail: [marco.rosso@polito.it](mailto:marco.rosso@polito.it)
Personal Website : http://rossomarcomartino.flazio.com/
PhD Student in Structural Civil Engineering at Politecnico di Torino

**Comment by Ayubirad** [comment] 2023-08-20 07:05
Dear @marco-rosso-m 

Thanks for your prompt response. Is this method applicable to both free decay responses (impact test) and ambient vibration cases, or is it specifically designed for ambient vibration scenarios only?

Best regards,
Mohammad

**Comment by marco-rosso-m** [comment] 2023-08-20 07:18
Dear @Ayubirad ,

Since the present code is based on the classic standard SSI-cov algorithm, from the theoretical point of view, this technique is belonging to OMA procedures for stationary signals. During impact tests, the impact itself and the subsequent free-decay are actually not stationary signals. 
However, as I know, in practice, many practitioners use this standard technique for analyzing this type of signal, despite from a theoretical point of view it is not correct at all. However, a slight variation of the SSI-cov is the NeXT-ERA algorithm which can be used also for non-stationary signals. See e.g. [4] Rainieri C, Fabbrocino G. Operational modal analysis of civil engineering structures. Springer Science+Business Media New York 2014; 2014 for more details.
Therefore, in our code, you can change the METHOD attribute in the file https://github.com/marco-rosso-m/i-AOMA/blob/main/ver_1.0/ssicov/constants.py from 1 to 2 in order to be able to use the NeXT-ERA algorithm for non-stationary signals.
https://github.com/marco-rosso-m/i-AOMA/blob/dfd69d6a5b09b5fe99b3a5a4cc3a1e63fb24dae0/ver_1.0/ssicov/helpers.py#L143

Obviously, be aware that more specific algorithms have been developed specifically for non-stationary signals, therefore the results with the NeXT-ERA may be not totally reliable sometimes and then dedicated techniques should be used.

Best regards

Marco Martino Rosso

ArtIStE - Artificial Intelligence in Structural Engineering
http://www.civilml.polito.it/
e-mail: [marco.rosso@polito.it](mailto:marco.rosso@polito.it)
Personal Website : http://rossomarcomartino.flazio.com/
PhD Student in Structural Civil Engineering at Politecnico di Torino

**Comment by Ayubirad** [comment] 2023-08-20 11:05
Dear @marco-rosso-m 

During plotting modeshapes `DATA/Sensors_locations_tower.txt` is used in `plot_mode_shapes.py`. Is the code written specifically for the tower example, or it can be used to plot the modeshapes of for example a bridge? If so how should it be defined?

Best regards,
Mohammad

**Comment by marco-rosso-m** [comment] 2023-08-22 10:26
Dear @Ayubirad , so far the code was written for the specific problem of plotting the Tower. However, I am working a part on defining a class to better manage plotting by idealizing the problems always in 3D to make it easier to get some simplified visual representation of the mode shapes. From that class, my idea is the possibility to get also 2D representation like section cuts in the wireframe model and visualize the mode shapes as arrows. However, I am still developing it and it is not published yet.

Best regards

Marco Martino Rosso

ArtIStE - Artificial Intelligence in Structural Engineering
http://www.civilml.polito.it/
e-mail: [marco.rosso@polito.it](mailto:marco.rosso@polito.it)
Personal Website : http://rossomarcomartino.flazio.com/
PhD Student in Structural Civil Engineering at Politecnico di Torino

**Closed as completed** 2023-08-22 19:20 UTC
